version: "3"

services:
  backend:
    build: .
    container_name: wego_backend
    depends_on:
      - mysql_db
      - redis
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=api.v1.app
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python3 -m api.v1.app

  mysql_db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wego_db
      MYSQL_USER: wegoride_user
      MYSQL_PASSWORD: wegoride
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: wego_ridis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
