version: "3"
services:
  backend:
    build: .
    container_name: wego_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  
  db:
    image: mysql:5.7
    container_name: wego_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wego_db
      MYSQL_USER: wegoride_user
      MYSQL-PASSWORD: wegoride
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  redis:
    image: redis:alpine
    container_name: wego_ridis
    ports:
      - "6379:6379"

volumes:
  db_data: