"""add ratings, vehicle plate number, driver license number

Revision ID: 73490d3f2357
Revises: d2e88db78d1a
Create Date: 2026-09-22 17:15:11.288324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73490d3f2357'
down_revision: Union[str, None] = 'd2e88db78d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('trip_id', sa.String(length=128), nullable=False),
    sa.Column('rater_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('rater_id', sa.String(length=128), nullable=False),
    sa.Column('ratee_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ratee_id', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_rating_score_range'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'rater_id', 'ratee_id', name='uq_rating_once_per_pair_per_trip')
    )
    op.add_column('drivers', sa.Column('license_number', sa.String(length=50), nullable=True))
    op.add_column('drivers', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('ratings_count', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'drivers', ['license_number'])
    op.add_column('riders', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('riders', sa.Column('ratings_count', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('plate_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'vehicles', ['plate_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_column('vehicles', 'plate_number')
    op.drop_column('riders', 'ratings_count')
    op.drop_column('riders', 'average_rating')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'ratings_count')
    op.drop_column('drivers', 'average_rating')
    op.drop_column('drivers', 'license_number')
    op.drop_table('ratings')
    # ### end Alembic commands ###
