"""add provider and provider_tx_ref to payments for chapa integration

Revision ID: 82ec4a127042
Revises: 73490d3f2357
Create Date: 2026-09-22 18:18:45.214257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ec4a127042'
down_revision: Union[str, None] = '73490d3f2357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider', sa.VARCHAR(length=60), nullable=True))
    op.add_column('payments', sa.Column('provider_tx_ref', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'payments', ['provider_tx_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'provider_tx_ref')
    op.drop_column('payments', 'provider')
    # ### end Alembic commands ###
