"""baseline schema

Revision ID: d2e88db78d1a
Revises: 
Create Date: 2026-09-22 11:27:07.912957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e88db78d1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('phone_number', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('reset_token', sa.String(length=250), nullable=True),
    sa.Column('admin_level', sa.Enum('superadmin', 'moderator'), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('drivers',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('phone_number', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('reset_token', sa.String(length=250), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=128), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('images',
    sa.Column('path', sa.String(length=250), nullable=False),
    sa.Column('user_type', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('locations',
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.VARCHAR(length=128), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('sender_id', sa.String(length=128), nullable=True),
    sa.Column('sender_type', sa.String(length=60), nullable=True),
    sa.Column('receiver_id', sa.String(length=128), nullable=True),
    sa.Column('receiver_type', sa.String(length=60), nullable=True),
    sa.Column('message', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('notification_type', sa.VARCHAR(length=128), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riders',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('phone_number', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('reset_token', sa.String(length=250), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=128), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('availabilities',
    sa.Column('driver_id', sa.String(length=128), nullable=True),
    sa.Column('location_id', sa.String(length=128), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('last_active_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('driver_id', sa.String(length=128), nullable=True),
    sa.Column('pickup_location_id', sa.String(length=128), nullable=True),
    sa.Column('dropoff_location_id', sa.String(length=128), nullable=True),
    sa.Column('pickup_time', sa.DateTime(), nullable=True),
    sa.Column('dropoff_time', sa.DateTime(), nullable=True),
    sa.Column('fare', sa.Float(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['dropoff_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('driver_id', sa.String(length=128), nullable=True),
    sa.Column('type', sa.VARCHAR(length=60), nullable=True),
    sa.Column('model', sa.VARCHAR(length=60), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=False),
    sa.Column('seating_capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('trip_id', sa.String(length=128), nullable=True),
    sa.Column('rider_id', sa.String(length=128), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=128), nullable=False),
    sa.Column('payment_time', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=128), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('total_payments',
    sa.Column('trip_id', sa.String(length=128), nullable=False),
    sa.Column('driver_id', sa.String(length=128), nullable=False),
    sa.Column('trip_fare', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('driver_earning', sa.Float(), nullable=True),
    sa.Column('driver_commission', sa.Float(), nullable=False),
    sa.Column('total_number_of_riders', sa.Integer(), nullable=True),
    sa.Column('number_of_riders_paid', sa.Integer(), nullable=True),
    sa.Column('number_of_riders_not_paid', sa.Integer(), nullable=True),
    sa.Column('transaction_over', sa.Boolean(), nullable=True),
    sa.Column('transaction_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_riders',
    sa.Column('trip_id', sa.String(length=128), nullable=False),
    sa.Column('rider_id', sa.String(length=128), nullable=False),
    sa.Column('is_past', sa.Boolean(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=128), nullable=True),
    sa.Column('status_by', sa.VARCHAR(length=128), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('trip_id', 'rider_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_riders')
    op.drop_table('total_payments')
    op.drop_table('payments')
    op.drop_table('vehicles')
    op.drop_table('trips')
    op.drop_table('availabilities')
    op.drop_table('riders')
    op.drop_table('notifications')
    op.drop_table('locations')
    op.drop_table('images')
    op.drop_table('drivers')
    op.drop_table('admins')
    # ### end Alembic commands ###
